### ISSUE TITLE
RHEL-07-020070 skipping

### ISSUE THREAD

**Issue by jasoncal108** [ansible/ansible-lockdown#13]
I am running the ansible-lockdown on a RHEL7 Server. I keep finding that RHEL-07-020070 is reporting as skipped in Ansible Tower. The target server's yum.conf definitely does not have repo_gpgcheck=1 but it does have gpgpcheck=1. I am deploying this in AWS on a RHEL AMI. Could this be a bug?

**Comment by shepdelacreme** [comment]
@jasoncal108 `gpgcheck` forces yum to perform a signature check on all RPM packages. `repo_gpgcheck` forces yum to perform a signature check on the repo metadata. 

The check/fix for RHEL-07-020070 is disabled by default in the current `defaults/main.yml`. See https://github.com/MindPointGroup/RHEL7-STIG/blob/8806d88fa3dc5a6cc4539e87a9c8a134b2a9e28e/defaults/main.yml#L23-L24

This is because RedHat does not currently sign their repo metadata. If you enable this STIG then it will break all yum functionality unless you configure the machine to use unofficial (non-RedHat) repos or if you/your company are providing custom repos through a Satellite server or something. 

For more info see the following links:
https://github.com/OpenSCAP/scap-security-guide/issues/1596
https://bugzilla.redhat.com/show_bug.cgi?id=1360939

**Comment by jasoncal121** [comment]
For others that are enabled with true, why is skipping happening?

**Comment by jasoncal121** [comment]
I've been running the playbook, and then i run a Nessus scan and many rules
that are supposed to be enabled don't seem to be applying

Jason

**Comment by shepdelacreme** [comment]
@jasoncal108 Hmm...it depends on the tasks that are being skipped but I imagine it is because many of the CAT 2 and CAT 3 tasks are currently not implemented. If you look in the `tasks/fix-cat2.yml` and `tasks/fix-cat3.yml` files you can see the currently not implemented tasks marked with a `- notimplemented` tag.

**Comment by jasoncal121** [comment]
So i see some are not implemented, but some stig settings are not according
to the requirements. For example RHEL-07-010180 is supposed to be set
to maxrepeat = 2, but in your repo it is set to 4. Could you explain why
this is?

Jason

**Comment by shepdelacreme** [comment]
This role was originally built from the draft STIG. There was a typo/error in this STIG IDs original text that specified 4 characters as the value. This task just needs to be updated now that Rev 1 of the STIG has been released.

**Comment by jasoncal121** [comment]
Ok, that can be easily changed but I am still finding over 100 results in
Nessus. It seems like I need to go one by one to resolve them.

Jason

**Comment by jasoncal121** [comment]
Is chrony set up? It is set to true and I see the configurations at the
bottom, but i notice that is being skipped. It doesn't have a tag as
'notimplemented'

Jason

**Comment by jasoncal121** [comment]
I see theres vars in 2 places in /defaults and /vars.. Why is it in 2
places? Also i noticed there is no handler. Any reason for that?

**Comment by juliedavila** [comment]
Personally, I've not contributed to the RHEL7 STIG work so I'll have to dig in a bit on the chrony piece but I have a couple things to add.

1. Please open up issues in the repo of the role you have an issue with in this case [here](https://github.com/MindPointGroup/RHEL7-STIG/issues). Issues in the `ansible-lockdown` shoudl be used to address broader issues that span multiple roles or higher level concepts (like, which baseline is next?)

2. When you do raise an issue please keep the issue on-topic. Your first issue was regarding `yum.conf`, then you mentioned `RHEL-07-010180`, and you've now recently started discussing an issue with the `chrony` related bits. 

Please open open a separate issue (in the [right repo](https://github.com/MindPointGroup/RHEL7-STIG/issues)) for each individual problem as that allows us to keep issues more cleanly linked with pull-requests and their commits.

If you're open to to essentially copy-pasting some of the bits you've already written to the right repo (as 3 separate issues) please let me know. If you dont have the time or desire, all the same, but I will close this issue and 'migrate' the issues over myself. Just let me know your preferene.
